# https://docs.docker.com/reference/compose-file/extension/
x-mounts: &mounts
  volumes:
    - /home/techbloc/.ssh:/opt/ssh
    - /home/techbloc/backups:/opt/backups


services:

  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_config:/config

  scheduler:
    <<: *mounts

  webserver:
    <<: *mounts

volumes:
  caddy_data:
  caddy_config:
