name: Lint and Test

on: pull_request

jobs:

  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files

  tests:
    runs-on: ubuntu-latest
    needs: static-checks
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v1
      - name: Run tests
        # Directory creation step required for testing
        env:
          SSH_DIRECTORY: /tmp/ssh
        run: |
          mkdir -p $SSH_DIRECTORY
          just build
          just test
